### ISSUE TITLE
Error raised when calling a raster with multiple data variables

### ISSUE THREAD

**Issue by njdepsky** [isciences/exactextract#56] opened 2023-12-08 01:08 UTC
Is there a way to run zone stats on a NetCDF file that has multiple data variables, while just referencing one of them in the `exactextract` call? I commonly construct NC files with multiple vars in xarray and realized that any with more than one data variable result in the following error:

`ERROR 10: Pointer 'hBand' is NULL in 'GDALGetRasterNoDataValue'.`

Example function call:
`exactextract -r "maxtemp:NETCDF:my_temp_dataset.nc[1]:maxtemp" -p gadm41_adm0.gpkg -f GID_0 -s "mean(var1)" -o output_test.csv`

The above functions as long as 'maxtemp' is the only data variable in the NC file, but if I have multiple (e.g. 'maxtemp, 'mintemp'), I get the above error. I'd like to avoid reading/writing separate NC files for each individual data variable in order to run exactextract, if possible. 

Thanks!

**Comment by dbaston** [comment] 2023-12-08 01:41
It works for me on the netCDF files I have with multiple variables. Do you have a file you can share so I can reproduce the error?

In the not-too-distant future you should be able to call exactextract on the xarray objects directly from Python.

**Comment by njdepsky** [comment] 2023-12-08 18:25
Sure thing. I just downloaded a single monthly average dewpoint 2m temperature NC file from ERA5 and then created a second data var that is 2x the 'd2m' values provided, and even copied the same attributes from the 'd2m' variable over to the newly created one.

[Uploading era5_d2m_modified.nc.zip…]()

**Comment by dbaston** [comment] 2023-12-10 02:00
This works for me:

```
exactextract -r "d2m:NETCDF:/home/dan/Downloads/era5_d2m_modified.nc:d2m[1]" -p /home/dan/data/gadm36_level_0.gpkg -f GID_0 -s "mean(d2m)" -o /tmp/test.csv
```

```
GID_0,d2m_mean
ABW,-nan
AFG,4685.02294921875
AGO,26304.724609375
AIA,-nan
ALA,3962.07885742188
...
```

This is the latest master version of exactextract? What is your platform / GDAL version?

**Comment by dbaston** [comment] 2023-12-12 18:34
> But I am getting a warning about a pybind11 path inconsistency upon running the cmake commmand when installing exact extract. 

It doesn't sound related, but please feel free to open an issue with the warning you're getting.

> How not-to-distant is this python package future?

It's committed to the repository, I just need to add a `setup.py` script. I don't have support direct `xarray` yet, though.

**Comment by dbaston** [comment] 2023-12-18 14:20
With https://github.com/isciences/exactextract/pull/59 you can do, e.g.

```
from exactextract import exact_extract
import fiona
import rioxarray
import xarray

xds = xarray.open_dataset('/tmp/era5.nc')

polys = fiona.open('/home/dan/data/ne_50m_admin_0_countries.shp')

results = exact_extract(xds['d2m'], polys, 'mean')
```

this will produce a result for each of the 24 values of the time dimension in the input file:

```
{'mean_band_24': 18229.251953125, 'mean_band_19': 17863.8671875, 'mean_band_17': 17598.78125, 'mean_band_16': 17715.302734375, 'mean_band_15': 17710.95703125, 'mean_band_14': 17716.79296875, 'mean_band_1': 17950.611328125, 'mean_band_5': 17924.5390625, 'mean_band_21': 18023.08984375, 'mean_band_20': 17962.734375, 'mean_band_3': 17834.9609375, 'mean_band_22': 18044.5859375, 'mean_band_4': 17862.849609375, 'mean_band_11': 17702.1640625, 'mean_band_6': 18000.875, 'mean_band_2': 17900.6875, 'mean_band_7': 18063.4453125, 'mean_band_8': 18098.9609375, 'mean_band_9': 18044.751953125, 'mean_band_23': 18175.9765625, 'mean_band_12': 17647.796875, 'mean_band_10': 18033.814453125, 'mean_band_18': 17675.703125, 'mean_band_13': 17668.837890625}}
```

**Closed** 2024-08-21 12:05 UTC
